// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZDjaULoKqSLgxYzyoRwpgfRhoCxUKxFY',
    appId: '1:922929499169:web:f831d6f28f1c38ff4da760',
    messagingSenderId: '922929499169',
    projectId: 'habitify-1b0cb',
    authDomain: 'habitify-1b0cb.firebaseapp.com',
    storageBucket: 'habitify-1b0cb.firebasestorage.app',
    measurementId: 'G-9BL462RMV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAriH0Cz9j2IVZX90OPEYRAUuB3kGqg9pc',
    appId: '1:922929499169:android:c3de391da306c8184da760',
    messagingSenderId: '922929499169',
    projectId: 'habitify-1b0cb',
    storageBucket: 'habitify-1b0cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUA2TOWP0rx3lMv-M0isGZPL5tPV2M9g8',
    appId: '1:922929499169:ios:cf72f2b01432d46a4da760',
    messagingSenderId: '922929499169',
    projectId: 'habitify-1b0cb',
    storageBucket: 'habitify-1b0cb.firebasestorage.app',
    iosClientId: '922929499169-ld6rnuppbnrhdnddedpu6tr8qojfgha1.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUA2TOWP0rx3lMv-M0isGZPL5tPV2M9g8',
    appId: '1:922929499169:ios:cf72f2b01432d46a4da760',
    messagingSenderId: '922929499169',
    projectId: 'habitify-1b0cb',
    storageBucket: 'habitify-1b0cb.firebasestorage.app',
    iosClientId: '922929499169-ld6rnuppbnrhdnddedpu6tr8qojfgha1.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZDjaULoKqSLgxYzyoRwpgfRhoCxUKxFY',
    appId: '1:922929499169:web:155c47e991fed4e74da760',
    messagingSenderId: '922929499169',
    projectId: 'habitify-1b0cb',
    authDomain: 'habitify-1b0cb.firebaseapp.com',
    storageBucket: 'habitify-1b0cb.firebasestorage.app',
    measurementId: 'G-NX0CJLQKMH',
  );
}
